# vim: sts=2 sw=2 et:

os: linux
dist: trusty
group: stable

language: cpp
services:
- docker

matrix:
  include:
    - env: "IMAGE=archlinux-build TARGETS=codecov"
    - env: "IMAGE=debian-build:latest TARGETS=headless-test"
    - env: "IMAGE=debian-build:testing TARGETS=headless-test"
    - env: "IMAGE=ubuntu-build:latest TARGETS=test"
    - env: "IMAGE=ubuntu-build:devel TARGETS=test"
    - env: "IMAGE=centos-build:latest TARGETS=headless-test"

script:
    - bash scripts/docker/exec.bash
