FROM debian:latest

RUN apt update \
	&& apt -y install build-essential
RUN apt -y install --no-install-recommends \
	cppcheck \
	libalut-dev \
	libcppunit-dev \
	libglew-dev \
	libglm-dev \
	libopenal-dev \
	libsdl2-dev \
	libsdl2-image-dev \
	libsdl2-net-dev \
	libsdl2-ttf-dev \
	zlib1g-dev \
	;
